### ISSUE TITLE
Updated structure and organized the files

### ISSUE THREAD

**Issue by K3ra-y** [UBC-MDS/DSCI_522_greenhouse_emissions_comparisons#10]
Hey Milly and Chao, 
I organized the existing files as Tiffany posted on slack and edited analysis related parts to make it more clear and consistent. Cheers :)

**Comment by chaomander2018** [comment]
Hi Kera, thank you so much! I just updated the release V1.0 so that your edit will be included in our v1.0 release.

**Comment by mkeyim** [comment]
Looks great!
