### ISSUE TITLE
the kernel density plot. Remove? Keep? integrate into other boxplot?

### ISSUE THREAD

**Issue by K3ra-y** [UBC-MDS/DSCI_522_greenhouse_emissions_comparisons#39]
I am hesitant keeping that plot since it doesn't add much to our results. If we want to show the distribution, we can add scatter point on to of the boxplot. Then we need to decide if it is too noisy or not to include. 
What do you think @mkeyim @chaomander2018 ?

**Comment by K3ra-y** [comment]
@chaomander2018 Yes, the GH_est_plot.png. I guess it is the violin plot.

**Comment by mkeyim** [comment]
I'll remove it, it does seem redundant
