### ISSUE TITLE
ANOVA table into .Rmd

### ISSUE THREAD

**Issue by K3ra-y** [UBC-MDS/DSCI_522_greenhouse_emissions_comparisons#40]
How do we in-bed ANOVA table into .Rmd?

**Comment by chaomander2018** [comment]
Hi @K3ra-y, 

I found this tool to covert csv table into Rmd. 
| term      | df  | sumsq       | meansq      | statistic   | p.value   | 
|-----------|-----|-------------|-------------|-------------|-----------| 
| Country   | 8   | 4.16876E+13 | 5.21095E+12 | 9591.925398 | 2.04E-280 | 
| Residuals | 225 | 1.22234E+11 | 543264362.5 | NA          | NA        | 

Does this work for you?

**Comment by K3ra-y** [comment]
I would be okay with this. However, for "reproducablity", we might get marks cut off (?)

I found this website. https://libscie.github.io/rmarkdown-workshop/handout.html
we need to make a code chunk, import data and `kable(ANOOVA_CSV, digits = 2)`.

However if this doesn't work, I would say le't not spend time on it. 
Does that sound good ? @mkeyim @chaomander2018

**Comment by K3ra-y** [comment]
ANOVA table is added manually. `kable` didn't work but if any one of you would like to try it working, by all means :)

27707e86b8e8e0c52c653dfec22b121e2e693e69
