### ISSUE TITLE
(v1.0) Need more meaningful commit messages

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI_522_greenhouse_emissions_comparisons#54]
@K3ra-y You have multiple commits with the message "Update README.md." Please be more specific.

**Comment by K3ra-y** [comment]
@aimirza I checked all my commits, I cannot find any of my commits with "Update README.md" message. Is this feedback for the group or specifically to me?

**Comment by aimirza** [comment]
Sorry, I meant @mkeyim. In v1.0, mkeymin has many commits that simply say "Update README.md." There are not meaningful commits.

**Comment by mkeyim** [comment]
Hi @aimirza , the majority of these commits were made when I first made the repo and was just changing around the title of the repo before I shared it with my teammates - however I get your point, I should have probably not done that and added more meaningful commits.
