### ISSUE TITLE
(v1.0) Messy README.md

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI_522_greenhouse_emissions_comparisons#56]
Please do not include the class proposal in your README.md.; it makes the document hard to read and messy. Write a clear description of your plan in paragraph format, not in list format.

**Comment by chaomander2018** [comment]
Addressed in [v2.2](https://github.com/UBC-MDS/DSCI_522_greenhouse_emissions_comparisons/releases/tag/V2.2)
