### ISSUE TITLE
(v1.0) Wrong question type. 

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI_522_greenhouse_emissions_comparisons#57]
Despite the fact that your data is longitudinal, your type of the question is not inferential, it is exploratory. Please review lecture 1 for the differences in question types.

**Comment by chaomander2018** [comment]
We are happy to discuss the type of question during the lab session this week. Thank you!

**Comment by K3ra-y** [comment]
Addressed [here](745562d2e0332219755a80eb87e4ccb6d857e291)
