### ISSUE TITLE
(v1.0) Total emission vs mean emissions

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI_522_greenhouse_emissions_comparisons#58]
What is the purpose of comparing the mean emissions between 1990 and 2015? It seems that comparing the total emissions between countries is more meaningful.

**Comment by K3ra-y** [comment]
@aimirza if we do that there will be one data point per each country and there wouldn't be a variation for each country therefore we cannot run ANOVA for testing the differences among the countries.

**Comment by aimirza** [comment]
If thats the case, then ANOVA is not the correct test.

**Comment by aimirza** [comment]
Perhaps you can choose a different meaningful question as we discussed today.

**Comment by K3ra-y** [comment]
Question is re-addressed on b4166e58421df959da7ee4577e1370f1358a9503
