### ISSUE TITLE
Peer Feedback

### ISSUE THREAD

**Issue by chaomander2018** [UBC-MDS/DSCI_522_greenhouse_emissions_comparisons#63]
- Think about the application of the analysis. How would we use our analysis result in the real world.

- There are countries that in the EU are included in the test. It confuses the reader that Netherlands, Finland and Denmarks are still in the analysis. We could have explain the data ambiguity.

- Country name overlapping in Figure 2.

**Comment by mkeyim** [comment]
We can just say we removed the aggregate group titled "European Union" and kept the individually labeled nations

**Comment by chaomander2018** [comment]
Yes, I think in our report we could be more specific. I can add some notes in the report this weekend.

**Comment by chaomander2018** [comment]
@K3ra-y @mkeyim I suggest we make a release after making changes to be on par with the milestone1 expectation and feedback. Make another release to be on par with the milestone 2 expectations.
