### ISSUE TITLE
Proposal Release

### ISSUE THREAD

**Issue by chaomander2018** [UBC-MDS/DSCI_522_greenhouse_emissions_comparisons#8]
Hi team, 
@KERA YUCEL @Miliban Keyim Hi ladies, I sent a merge request to the repo, once I get your approval/merge, we can publish the drafted release. 

Cheers,

**Comment by mkeyim** [comment]
Looks good to me!

**Comment by chaomander2018** [comment]
Pull request merged.

**Comment by chaomander2018** [comment]
I closed the issue and released v0,1. @mkeyim  I changed your yesterday release tag to v0.0 so that we can get the latest version as v0.1. (github doesn’t allow duplicate release name). Thank you team!
