### ISSUE TITLE
Milestone3 Progress

### ISSUE THREAD

**Issue by chaomander2018** [UBC-MDS/DSCI_522_greenhouse_emissions_comparisons#83]
Hi team, 
-The dependency diagram is done. 
-I edited the docker file and tested twice it worked. 

@mkeyim, you can get rid of everything you installed this afternoon. If you follow the instructions it should work fine and fast. 

Could you two kindly test it? @K3ra-y @mkeyim .

Thank you for your patience

**Comment by mkeyim** [comment]
Tested it and it works wonderfully! Let's make sure @K3ra-y can run it on her PC as I also have a Mac
